# Alacritty Configuration
# Based on your Wezterm setup

import = ["colors.toml", "keybinds.toml"]

# Window configuration
[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 8, y = 6 }
opacity = 0.85
decorations = "none"
startup_mode = "Windowed"

# Font configuration (matching your Wezterm setup)
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

size = 13.0

# Fallback fonts
[[font.features]]
family = "JetBrainsMono Nerd Font"
features = ["liga", "calt"]

# Cursor configuration
[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true
thickness = 0.15

# Scrolling
[scrolling]
history = 10000
multiplier = 3

# Bell
[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

# Selection
[selection]
save_to_clipboard = true

# Live config reload
[live_config_reload] = true

# Terminal configuration
[terminal]
osc52 = true
bell = { animation = "EaseOutExpo", duration = 0, color = "#ffffff" }

# Mouse
[mouse]
hide_when_typing = true

# Hints
[hints.enabled]
alphabet = "jfkdls;ahgurieowpq"
min_length = 1
max_length = 128

# Performance tuning
[performance]
max_dirty_lines = 1000

# Debug
[debug]
log_level = "Warn"
print_events = false
persistent_logging = false
