# Alacritty Keybinds
# Replicating Wezterm functionality

# Copy and paste (matching your Wezterm ALT-based setup)
[[keybind]]
key = "c"
mods = "Alt"
action = "Copy"

[[keybind]]
key = "v"
mods = "Alt"
action = "Paste"

[[keybind]]
key = "a"
mods = "Alt"
action = "SelectAll"

# Pane splitting (matching Wezterm)
[[keybind]]
key = "\\"
mods = "Alt"
action = "SpawnNewInstance"

# Close terminal
[[keybind]]
key = "w"
mods = "Alt"
action = "Quit"

# Font size adjustments
[[keybind]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keybind]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keybind]]
key = "0"
mods = "Control"
action = "ResetFontSize"

# Scrollback
[[keybind]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keybind]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

[[keybind]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"

[[keybind]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"

# Line movement
[[keybind]]
key = "Up"
mods = "Shift"
action = "ScrollLineUp"

[[keybind]]
key = "Down"
mods = "Shift"
action = "ScrollLineDown"

# Search
[[keybind]]
key = "f"
mods = "Control"
action = "SearchForward"

[[keybind]]
key = "b"
mods = "Control"
action = "SearchBackward"

# Vi mode (if enabled)
[[keybind]]
key = "Space"
mods = "Control|Shift"
action = "ToggleViMode"

# Window management
[[keybind]]
key = "n"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keybind]]
key = "Enter"
mods = "Alt"
action = "SpawnNewInstance"

# Fullscreen
[[keybind]]
key = "F11"
action = "ToggleFullscreen"

# Debug
[[keybind]]
key = "d"
mods = "Control|Shift"
action = "DebugConfig"

# Reload config
[[keybind]]
key = "r"
mods = "Control|Shift"
action = "ReloadConfig"
