# Custom Dark Theme for WezTerm
# A modern dark theme inspired by GitHub's color palette

[colors]
# Basic colors
foreground = "#e6e6e6"
background = "#0d1117"

# Cursor colors
cursor_bg = "#58a6ff"
cursor_fg = "#0d1117"
cursor_border = "#58a6ff"

# Selection colors
selection_fg = "#0d1117"
selection_bg = "#58a6ff"

# Scrollbar
scrollbar_thumb = "#21262d"

# Split lines
split = "#21262d"

# ANSI colors
ansi = [
  "#484f58",  # black
  "#f85149",  # red
  "#3fb950",  # green
  "#d29922",  # yellow
  "#58a6ff",  # blue
  "#bc8cff",  # magenta
  "#39d353",  # cyan
  "#b1bac4",  # white
]

# Bright ANSI colors
brights = [
  "#6e7681",  # bright black
  "#ff7b72",  # bright red
  "#56d364",  # bright green
  "#e3b341",  # bright yellow
  "#79c0ff",  # bright blue
  "#d2a8ff",  # bright magenta
  "#56d364",  # bright cyan
  "#f0f6fc",  # bright white
]

# Tab bar colors
[colors.tab_bar]
background = "#0d1117"

[colors.tab_bar.active_tab]
bg_color = "#21262d"
fg_color = "#f0f6fc"
intensity = "Normal"
underline = "None"
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab]
bg_color = "#0d1117"
fg_color = "#7d8590"
intensity = "Normal"
underline = "None"
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab_hover]
bg_color = "#21262d"
fg_color = "#b1bac4"
italic = true

[colors.tab_bar.new_tab]
bg_color = "#0d1117"
fg_color = "#7d8590"

[colors.tab_bar.new_tab_hover]
bg_color = "#21262d"
fg_color = "#b1bac4"
italic = true

# Copy mode colors
[colors.copy_mode_active_highlight_bg]
Color = "#58a6ff"

[colors.copy_mode_active_highlight_fg]
Color = "#0d1117"

[colors.copy_mode_inactive_highlight_bg]
Color = "#21262d"

[colors.copy_mode_inactive_highlight_fg]
Color = "#b1bac4"

# Quick select colors
[colors.quick_select_label_bg]
Color = "#58a6ff"

[colors.quick_select_label_fg]
Color = "#0d1117"

[colors.quick_select_match_bg]
Color = "#21262d"

[colors.quick_select_match_fg]
Color = "#f0f6fc"
